Added support for labels and existing PR check (v2 from master)
thomaseizinger/create-pull-request pull request #61
Opened 2021-07-23 07:04 UTC by vitalyal

2021-07-23 08:09 UTC, thomaseizinger requested changes
Unfortunately, not all the checks are passing currently (even ignoring the "reviewers" check): https://github.com/vitalyal/create-pull-request/actions/runs/1058829910

2021-07-23 08:09 UTC, thomaseizinger commented on CHANGELOG.md
> -[Unreleased]: https://github.com/thomaseizinger/create-pull-request/compare/1.0.0...HEAD
As mentioned in the other PR, this needs to stay.

I'll update the master branch on my repo and then you can rebase / merge.

2021-07-23 11:04 UTC, vitalyal commented
I've rebased, updated changelog and fixed CI (the only case failing is about reviewers) https://github.com/vitalyal/create-pull-request/actions/runs/1059421040

2021-07-24 13:21 UTC, merged

2021-07-24 13:21 UTC, thomaseizinger commented
> I've rebased, updated changelog and fixed CI (the only case failing is about reviewers) https://github.com/vitalyal/create-pull-request/actions/runs/1059421040

Thank you! I'll release a new version soon!

2021-07-26 07:57 UTC, thomaseizinger commented
Released as 1.2.0.